runtime: php55
api_version: 1

env_variables:
  MYSQL_DSN: mysql:unix_socket=/cloudsql/lazzyworks-185201:asia-northeast1:lazzyworksdb;dbname=lazycorporation-ofwdatabase
  MYSQL_USER: root
  MYSQL_PASSWORD: root

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|ico))$
  static_files: \1
  upload: .+\.(gif|png|jpg|ico)$
  application_readable: true

- url: /(.+\.css)$
  script: \1
  
- url: /(.+\.js)$
  script: \1
  
  
# Serve php scripts.
- url: /(.+\.php)$
  script: \1
  
- url: /.*
  script: index.php
